WITH base AS (
  SELECT PARSE_DATE('%Y%m%d', event_date) AS d, user_pseudo_id AS uid, event_name AS ev,
         (SELECT value.string_value FROM UNNEST(event_params) WHERE key='feature_name') AS fname
  FROM `iip055-genius.analytics_523266340.events_intraday_*`
)
SELECT FORMAT_DATE('%Y-%m-%d', d) AS d, COUNT(DISTINCT uid) AS user_active,
  COUNT(DISTINCT IF(ev='home_view', uid, NULL)) AS enhance__home_view,
  COUNT(DISTINCT IF(ev='enhan_upload_photo_view', uid, NULL)) AS enhance__upload,
  COUNT(DISTINCT IF(ev='enhan_scanning_view', uid, NULL)) AS enhance__scanning,
  COUNT(DISTINCT IF(ev='enhan_analy_view', uid, NULL)) AS enhance__analyze,
  COUNT(DISTINCT IF(ev='service_request' AND fname='Enhance', uid, NULL)) AS enhance__generate,
  COUNT(DISTINCT IF(ev='iap_view' AND fname='Enhance', uid, NULL)) AS enhance__paywall,
  COUNT(DISTINCT IF(ev='enhan_result_ld_view', uid, NULL)) AS enhance__result_loading,
  COUNT(DISTINCT IF(ev='enhan_result_view', uid, NULL)) AS enhance__result,
  COUNT(DISTINCT IF(ev='enhan_result_download_click', uid, NULL)) AS enhance__download,
  COUNT(DISTINCT IF(ev='enhan_result_share', uid, NULL)) AS enhance__share,
  COUNT(DISTINCT IF(ev='home_view', uid, NULL)) AS i2i__home_view,
  COUNT(DISTINCT IF(ev='home_style_click' AND fname='I2I', uid, NULL)) AS i2i__click_style,
  COUNT(DISTINCT IF(ev='i2i_upload_photo_view', uid, NULL)) AS i2i__upload,
  COUNT(DISTINCT IF(ev='service_request' AND fname='I2I', uid, NULL)) AS i2i__generate,
  COUNT(DISTINCT IF(ev='iap_view' AND fname='I2I', uid, NULL)) AS i2i__paywall,
  COUNT(DISTINCT IF(ev='i2i_result_ld_view', uid, NULL)) AS i2i__result_loading,
  COUNT(DISTINCT IF(ev='i2i_result_view', uid, NULL)) AS i2i__result,
  COUNT(DISTINCT IF(ev='i2i_result_download_click', uid, NULL)) AS i2i__download,
  COUNT(DISTINCT IF(ev='i2i_result_share', uid, NULL)) AS i2i__share,
  COUNT(DISTINCT IF(ev='home_view', uid, NULL)) AS i2v__home_view,
  COUNT(DISTINCT IF(ev='home_style_click' AND fname='I2V', uid, NULL)) AS i2v__click_style,
  COUNT(DISTINCT IF(ev='i2v_upload_photo_view', uid, NULL)) AS i2v__upload,
  COUNT(DISTINCT IF(ev='service_request' AND fname='I2V', uid, NULL)) AS i2v__generate,
  COUNT(DISTINCT IF(ev='iap_view' AND fname='I2V', uid, NULL)) AS i2v__paywall,
  COUNT(DISTINCT IF(ev='i2v_result_ld_view', uid, NULL)) AS i2v__result_loading,
  COUNT(DISTINCT IF(ev='i2v_result_view', uid, NULL)) AS i2v__result,
  COUNT(DISTINCT IF(ev='i2v_result_download_click', uid, NULL)) AS i2v__download,
  COUNT(DISTINCT IF(ev='i2v_result_share', uid, NULL)) AS i2v__share,
  COUNT(DISTINCT IF(ev='tryon_entry_click', uid, NULL)) AS tryon__entry,
  COUNT(DISTINCT IF(ev='tryon_preview_view', uid, NULL)) AS tryon__preview,
  COUNT(DISTINCT IF(ev='tryon_upload_photo_success', uid, NULL)) AS tryon__upload_ok,
  COUNT(DISTINCT IF(ev='tryon_preview_team_click', uid, NULL)) AS tryon__team_click,
  COUNT(DISTINCT IF(ev='iap_view' AND fname='Try-on Jersey', uid, NULL)) AS tryon__paywall,
  COUNT(DISTINCT IF(ev='tryon_preview_save_click', uid, NULL)) AS tryon__save,
  COUNT(DISTINCT IF(ev='tryon_preview_share_click', uid, NULL)) AS tryon__share,
  COUNT(DISTINCT IF(ev='wclooks_entry_click', uid, NULL)) AS wclooks__entry,
  COUNT(DISTINCT IF(ev='wclooks_view', uid, NULL)) AS wclooks__view,
  COUNT(DISTINCT IF(ev='wclooks_upload_photo_success', uid, NULL)) AS wclooks__upload_ok,
  COUNT(DISTINCT IF(ev='wclooks_style_click', uid, NULL)) AS wclooks__style_click,
  COUNT(DISTINCT IF(ev='iap_view' AND fname='World Cup Looks', uid, NULL)) AS wclooks__paywall,
  COUNT(DISTINCT IF(ev='wclooks_save_click', uid, NULL)) AS wclooks__save,
  COUNT(DISTINCT IF(ev='wclooks_share_click', uid, NULL)) AS wclooks__share,
  COUNT(DISTINCT IF(ev='wcvideo_entry_click', uid, NULL)) AS wcvideo__entry,
  COUNT(DISTINCT IF(ev='wcvideo_grid_view', uid, NULL)) AS wcvideo__grid,
  COUNT(DISTINCT IF(ev='wcvideo_upload_photo_view', uid, NULL)) AS wcvideo__upload_view,
  COUNT(DISTINCT IF(ev='wcvideo_upload_photo_success', uid, NULL)) AS wcvideo__upload_ok,
  COUNT(DISTINCT IF(ev='wcvideo_generating_view', uid, NULL)) AS wcvideo__generating,
  COUNT(DISTINCT IF(ev='wcvideo_result_view', uid, NULL)) AS wcvideo__result,
  COUNT(DISTINCT IF(ev='wcvideo_result_save_click', uid, NULL)) AS wcvideo__save,
  COUNT(DISTINCT IF(ev='wcvideo_result_share_click', uid, NULL)) AS wcvideo__share
FROM base GROUP BY ROLLUP(d) ORDER BY d
